#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions

cleanCase                      # removes mesh, results, logs; keeps 0/
rm -rf .0.keep
rm -rf constant/extendedFeatureEdgeMesh constant/triSurface/*.eMesh
rm -f system/meshParameters
rm -rf postProcessing
#------------------------------------------------------------------------------
